name: My GitHub Actions Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Display Workflow Name
        run: |
          echo "This workflow is named ${{ github.action }}"
