name: list environment variables

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: $DAY_OF_WEEK == 'Monday'
        run: echo ${{ github.repository }}
        env:
          First_Name: Mona


