name: My GitHub Actions Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: test github action env var
        run: echo "${{ github.action }}"

      # echo "This workflow is named ${{ github.action }}"
