name: tests

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    #  - name: Checkout Repository 
    #   uses: actions/checkout@v4

      - name: GITHUB_EVENT_PATH
        id: step_one
        run: |
            echo "$GITHUB_EVENT_PATH"
      - name: View Event JSON
        run: cat $GITHUB_EVENT_PATH
