name: name of the action currently running

on: workflow_dispatch

jobs:
  job_name:
    runs-on: ubuntu-latest
    
    steps:
    - name: my first name step
      id: my first id step
      run: echo ${{ github.action }}


