name: My GitHub Actions Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
         node:16
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Workflow Name
        run: |
          echo "This workflow is named ${{ github.action }}"
