name: list environment variables

on:
  workflow_dispatch

jobs:
  env_var_test_job:
    runs-on: ubuntu-latest
    steps:
     - name: "list the entire set of environment variables"
       run: echo $GITHUB_WORKSPACE

