name: tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
     SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
    
    steps:
      - name: Set color
        id: color-selector
        run:    echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT" 
      - name: Get color
        env:
         SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR" 

  build2:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: survived first job
        id: second_job
        env:
         lastjob_output: ${{ needs.build.outputs.SELECTED_COLOR }}
        run: echo "The selected color from previous job is $lastjob_output" 
             echo "$lastjob_output survived first job!"


        
