name: My GitHub Actions Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        env:
         g_a_r: ${{ github.action.repository }}
          
      - name: Display owner and repository name of action
        run: |
          echo "This workflow is named $g_a_r"
