name: tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
    - name: Set color
      run: echo "current branch is $GITHUB_REF_TYPE"

        
