name: tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
    - name: Set color
      env:
        test: ${{ github.ref }}
      run: echo "current branch is $test"

        
