name: My GitHub Actions Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository and  Set Environment Variable
        uses: actions/checkout@v4
        env:
          MY_VARIABLE: ${{ GITHUB.ACTION.REPOSITORY }}

      - name: Use Environment Variable
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}"
