name: name of the action currently running

on: workflow_dispatch

jobs:
  job_name:
    runs-on: ubuntu-latest
    
    steps:
    - name: Use local hello-world-action
      uses: ./.github/actions/hello-world-action
    - name: my first name step
      run: echo ${{ github.action }}


