name: rerun test workflow
on: workflow_dispatch

permissions: read-all
        
jobs:
#job_id value is: my_rerun_job
  my_rerun_job:
          runs-on: ubuntu-latest
          steps:
           - name: Checkout repository
             uses: actions/checkout@v4
           - run: gh api \
                  --method POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/jobs/jobs.my_rerun_job/rerun --body "is this necessary here?"
              env: 
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               OWNER: ${{ github.repository_owner }}
               REPO: ${{ github.event.repository.name }}

  
# - run: gh pr comment $PR_URL --body "Welcome to the repository!"
#   env:
#    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#    PR_URL: ${{ github.event.pull_request.html_url }}
