name: rerun 1
on:
  workflow_dispatch:
jobs:
  rerun:
       runs-on: ubuntu-latest
       permissions: {}
       steps:
        - uses: actions/checkout@v4
        - env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_OWNER_AND_REPO: ${{ github.repository }}
       
        - run: |
           curl -L \
           -X POST \
           -H "Authorization: Bearer $GH_TOKEN" \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           --url "https://api.github.com/repos/$GH_OWNER_AND_REPO/actions/jobs/jobs.use_api/rerun" 
